### ISSUE TITLE
GCC 9.3.0 is failing to compile roudi_app.cpp

### ISSUE THREAD

**Issue by marthtz** [eclipse/iceoryx#326]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 9.3

**Observed result or behaviour:**
GCC 9.3 is failing to compile `roudi_app.cpp`:
```
/iceoryx/iceoryx_posh/source/roudi/application/roudi_app.cpp: In member function 'void iox::roudi::RouDiApp::parseCmdLineArguments(int, char**, iox::roudi::CmdLineParser::CmdLineArgumentParsingMode)':
/iceoryx/iceoryx_posh/source/roudi/application/roudi_app.cpp:180:19: error: use of deleted function 'constexpr iox::roudi::CmdLineParser::CmdLineParser()'
  180 |     CmdLineParser cmdLineParser;
      |                   ^~~~~~~~~~~~~

In file included from /iceoryx/iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp:19,
                 from /iceoryx/iceoryx_posh/source/roudi/application/roudi_app.cpp:15:
/iceoryx/iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp:46:5: note: 'constexpr iox::roudi::CmdLineParser::CmdLineParser() noexcept' is implicitly deleted because its exception-specification does not match the implicit exception-specification 'noexcept (false)'
   46 |     CmdLineParser() noexcept = default;
```

**Expected result or behaviour:**
Can compile

**Conditions where it occurred / Performed steps:**
Compile with GCC 9.3

**Comment by elBoberido** [comment]
Weird. I can compile it with GCC 9.3 on Ubuntu 20.04 and @elfenpiff on gentoo. Can you verify that it fails on master?

**Comment by elfenpiff** [comment]
I verified it just now and it compiles with the current master!
Verified compiler versions:
   - gcc-9.3.0 (Gentoo)
   - gcc-10.2.0 (@FerdinandSpitzschnueffler on ArchLinux)
   - clang-10.0.1 (Gentoo)

I would close the issue or @marthtz do you have any additional information on howto reproduce this bug?

**Comment by elfenpiff** [comment]
@marthtz any news? Does the bug still persist?

**Comment by marthtz** [comment]
Ok, that's good news. Basically, I just forwarded the issue as I don't have a working Ubuntu 20 setup right now. As @elBoberido and @elfenpiff confirm it's working on various systems I'll close the issue!
Thanks for checking guys!
